services:
  - type: web
    name: personal-ai-tools
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    plan: free
    autoDeploy: false
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
